apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcart-service
  template:
    metadata:
      labels:
        app: shoppingcart-service
    spec:
      containers:
        - name: shoppingcart-service
          image: allenwu1/shoppingcart-service:latest
          ports:
            - containerPort: 8086
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"