apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-service
spec:
  type: NodePort
  selector:
    app: shoppingcart-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086